image:
  file: gitpod/gitpod.Dockerfile

#tasks:
#  - command: exercism configure --token= --workspace=/workspace/rust-exercism

# vscode:
#   extensions:
#   - hashicorp.terraform
#   - ms-python.python